<p>
在<code>finally</code>中执行return，会影响所有从<code>try</code>或<code>catch</code>中抛出的未处理的<code>Throwable</code>向外传播。
</p>

<p>
下列代码演示了这个规则。
开发者期望在控制台获得"ERROR"，但显示的是"OK"。
</p>

<pre>
public static void main(String[] args) {
  try {
    doSomethingWhichThrowsException();
    System.out.println("OK");
  } catch (RuntimeException e) {
    System.out.println("ERROR");
  }
}

public static void doSomethingWhichThrowsException() {
  try {
    throw new RuntimeException();
  } finally {
    /* ... */
    return;                                        // Non-Compliant - prevents the RuntimeException from being propagated
  }
}
</pre>
